### PR TITLE
ziomon: fix typo

### PR DESCRIPTION
**Pull request by r4f4**
Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

### CODE REVIEW

**Comment by michael-holzheu** [comment]
@r4f4 Thanks for the fix, but from the patch (at least) I don't understand what exactly the problem/symptom is.

**Comment by r4f4** [comment]
In the case of `check_host_param' and `init_adapters', it won't detect the absence of 'queue_full' in an old kernel installation since the stat call will always succeed at that point because it's checking against a path that was already verified to exist. Now, if that's going to cause any visible symptoms I can't tell since I'm not familiar enough with the code.

**Comment by Benjamin-Block** [comment]
Nice catch, these seem to be copy&paste mistakes. I think the changes are fine, but Steffen is the maintainer of the tools.

There is no impact on how the tools work, but in case the 'queue_full' attribute doesn't exist for a very old kernels, they make ziomon exit gracefully.

**Comment by r4f4** [comment]
I'll update the patch with a rationale if you think it's worth merging.

**Comment by Benjamin-Block** [comment]
Well, as long as the code is still in ziomon - and I don't see it disappearing anytime soon - it would be good to have it correct :-). Even though I'm not sure anyone still uses such old kernels where this attribute doesn't already exist.

**Comment by r4f4** [comment]
I updated the patch description. Thank you for looking into it @michael-holzheu and @Benjamin-Block.

**Comment by michael-holzheu** [comment]
> I updated the patch description. Thank you for looking into it @michael-holzheu and @Benjamin-Block.

Looks good to me now :thumbsup:, thanks!

**Comment by steffen-maier** [comment]
@r4f4 thanks for the fix, will integrate it

**Pull request closed without merging**
