### PR TITLE
WIP: #5: rewrite zipl_helper in python.

### PR DESCRIPTION
**Pull request by r4f4**
This is still a work in progress regarding issue #5. The C version would take longer than expected, so I did a python one in the meantime. Using python is still in line with the Fedora minimal baseruntime, since it is a dependency of some basic system tools (like dnf).

I tried to included some unit tests to make sure the helper works as expected. I'll continue testing and improving the test cases while upstream reviews this patch.

I would love some feedback before submitting the definitive version.

### CODE REVIEW

**Comment by r4f4** [comment]
ping. Any comments on this?

**Comment by michael-holzheu** [comment]
> ping. Any comments on this?

@r4f4 - sorry for the late reply.

Our strategy for s390-tools is to use C as the main language. Therefore we started converting tools (lsqeth, lsscm, lschp, chchp) to C and started with the internal "libutil" support library. Having only one language makes support much easier since all of our developers know C and sharing code is possible.

Up to now we don't have python in s390-tools. So if we go your way, this would add yet another language to the package which I really would like to avoid.

Therefore I would appreciate it if you could try to re-implement the script in C.

**Comment by michael-holzheu** [comment]
@oberpar @stefan-haberland @hoeppnerj : FYI

**Comment by r4f4** [comment]
Ok. I'll keep working on the C version.

**Comment by michael-holzheu** [comment]
> Ok. I'll keep working on the C version.

Great :+1:

**Pull request closed without merging**
